### PR TITLE
Feat: Create schema

### PR DESCRIPTION
**Pull request by Amrhub**
In this PR I Implemented the schema for the given [ERD Diagram](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/images/blog_app_erd.png)

### CODE REVIEW

**Comment by Amrhub** [comment]
# Question! 🤔 
In the ERD Diagram, the foreign key names are different from the naming convention of rails. e.g `AuthorID` and the auto-magically generated one will be `user_id` as shown, My question is how can I change that or shouldn't I?
image

**Comment by DeliceLydia** [comment]
Hello @Amrhub, Don't worry this is not an issue keep it that way

**Review by DeliceLydia — APPROVED** [review]
# Congratulations! 🎉🎉 

## Hi @Amrhub, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Amrhub** [comment]
@DeliceLydia  Thank you ☺️

**Pull request merged**
