### PR TITLE
Feat: authentication

### PR DESCRIPTION
**Pull request by Amrhub**
In this PR: 
I made an authentication setup with devise.
make users can't browse in `posts` or `users` unless he is signed in.

### CODE REVIEW

**Comment by Amrhub** [comment]
Hello, dear code reviewer!

note: I couldn't get stmp email to actually send an email. It's currently working on console and functional would be grateful if you have an idea of how to make it work without directly using my email, do you?

**Review by Dipeshtwis — APPROVED** [review]
Hi @Amrhub, 

Everything is working fine.
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Amrhub** [comment]
Thank you@Dipeshtwis! I think you missed my question 

```

Hello, dear code reviewer!

note: I couldn't get stmp email to actually send an email. It's currently working on console and functional 
I will be grateful if you have an idea of how to make it work without directly using my email, do you?
```

**Comment by Dipeshtwis** [comment]
> Thank you@Dipeshtwis! I think you missed my question
> 
> ```
> 
> Hello, dear code reviewer!
> 
> note: I couldn't get stmp email to actually send an email. It's currently working on console and functional 
> I will be grateful if you have an idea of how to make it work without directly using my email, do you?
> ```

Hi @Amrhub,

Sorry for missing your question. Since I have not worked much on sending email yet, you can use [this article ](https://dev.to/morinoko/sending-emails-in-rails-with-action-mailer-and-gmail-35g4) to know more. You can also book a 1:1 session with the Senior code reviewer as well. 

Hope this give some idea 
Thanks

**Comment by Amrhub** [comment]
> > Thank you@Dipeshtwis! I think you missed my question
> > ```
> > 
> > Hello, dear code reviewer!
> > 
> > note: I couldn't get stmp email to actually send an email. It's currently working on console and functional 
> > I will be grateful if you have an idea of how to make it work without directly using my email, do you?
> > ```
> 
> Hi @Amrhub,
> 
> Sorry for missing your question. Since I have not worked much on sending email yet, you can use [this article ](https://dev.to/morinoko/sending-emails-in-rails-with-action-mailer-and-gmail-35g4) to know more. You can also book a 1:1 session with the Senior code reviewer as well.
> 
> Hope this give some idea Thanks

**Pull request merged**
